name = "TINABW - This is not a beatiful World"
author = "ZKLaurin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "270c25b3eef16e9f78a9d59537f5186c36f3eb93e1e0a6787f52bceb37cc5517"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
